### 2. Obtener lista de usuarios (Ruta protegida)
GET http://localhost:3000/api/rol
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOjEsImVtYWlsIjoidXN1YXJpb0BlamVtcGxvLmNvbSIsInJvbF9pZHJvbCI6MSwibm9tYnJlY2xpZW50ZSI6Ikp1YW4gUMOpcmV6Iiwicm9sIjoiQWRtaW5pc3RyYWRvciIsImlhdCI6MTc0MjAwNDEwMSwiZXhwIjoxNzQyMDA1MDAxfQ.WTV5P1_MkyCoYIt03rzVEkdJ8JwuiWy4yzo9RpmgKiA
Content-Type: application/json

### 1. Iniciar sesión (Ruta pública)
POST https://napi-production.up.railway.app/api/usuario/login
Content-Type: application/json

{
  "email": "usuario@ejemplo.com",
  "contraseña": "contra123"
}

