POST  https://napi-production.up.railway.app/api/usuario/logout
Content-Type: application/json 

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOjEsImVtYWlsIjoidXN1YXJpb0BlamVtcGxvLmNvbSIsInJvbF9pZHJvbCI6MSwibm9tYnJlIjoiQWRtaW5pc3RyYWRvciIsImlhdCI6MTc0MTg0MzQ4NiwiZXhwIjoxNzQyNDQ4Mjg2fQ.RrVUZFk1rjATWH61Aa54R9FNfKFWbV6OQHHhE6Pv7ZE"
}


